# Generated by Django 4.2.1 on 2023-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('username', models.CharField(max_length=60, verbose_name='никнейм')),
                ('position', models.CharField(choices=[('модель', 'Модель'), ('оператор', 'Оператор')], max_length=30, verbose_name='позиция')),
                ('location', models.CharField(max_length=100, verbose_name='локация')),
                ('work_start_time', models.TimeField(verbose_name='начало смены')),
                ('rest_day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (6, 'Воскресенье')], null=True, verbose_name='выходной')),
                ('active', models.BooleanField(default=False, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'работники',
            },
        ),
    ]
